### ISSUE TITLE
Incorrect repository url

### ISSUE THREAD

**Issue by kindred** [Yelp/puppet-uchiwa#70]
They repo URL in the module is pointing to repos.sensuapp.org, which no longer works. The documentation on the website (https://sensuapp.org/docs/latest/install-repositories) says repositories.sensuapp.org.

Rob

**Comment by solarkennedy** [comment]
Hmm. We need to junk repos all together like we do with debian? and just piggyback on the Sensu' modules repo. @kindred if you get this working can you open a PR?

**Comment by solarkennedy** [comment]
Hmm. We need to junk repos all together like we do with debian? and just piggyback on the Sensu' modules repo. @kindred if you get this working can you open a PR?

**Comment by kindred** [comment]
I ended up using the sensu modules repo.
