### ISSUE TITLE
Commit caused regression

### ISSUE THREAD

**Issue by bahner** [Yelp/puppet-uchiwa#74]
commit b76eac99511139ba9eac1e7669c640b9704c2f3 seems to create a redundant comma, that creates an invalid uchiwa.json. Uchiwa starts with the following error:

{"Date":"2016-06-14T11:21:39.126584744Z","Level":"fatal","Src":{"Func":"github.com/sensu/uchiwa/uchiwa/config.Load","Line":48},"Output":"Error decoding file /etc/sensu/uchiwa.json: invalid character '}' looking for beginning of object key string"}

**Comment by solarkennedy** [comment]
Ah crap. We probably need generating the json with ruby instead of via strings in the template.

**Comment by solarkennedy** [comment]
Do you know if this is still an issue?

**Comment by bahner** [comment]
I can confirm that it's not a probøem for me anymore. :-)
