### ISSUE TITLE
Service enable loop

### ISSUE THREAD

**Issue by dzeleski** [Yelp/puppet-uchiwa#76]
Not exactly sure whats going on here but on RHEL 7 I am seeing on every puppet run the uchiwa service trying to be enabled for boot. In order to fix the problem I set the class to stop managing its services and did my own notify and service declaration:

https://github.com/Yelp/puppet-uchiwa/blob/master/manifests/service.pp

```
class { '::uchiwa':
    install_repo        => false,
    user                => 'sensu',
    pass                => 'sensu',
    port                => '3000',
    sensu_api_endpoints => $uchiwa_api_config,
    manage_services     => false,
    notify              => Service['uchiwa'],
  }
   service { ['uchiwa']:
    ensure   => 'running',
    enable   => true,
    provider => 'redhat',
  }
```

Also as a side note init.pp has better documentation then the readme file does. It would be cool if that could get ported over or at least an FYI stating there is more info there.

**Comment by solarkennedy** [comment]
Do you know if this is still going on?

**Comment by dzeleski** [comment]
We moved to enterprise and I dont have this issue there but we are not using this module anymore so I could not say unfortunately.

**Comment by jaxxstorm** [comment]
Doesn't happen for me, I think it was an issue with the systemd unit/init.d script in the old uchiwa releases. I think it can be closed
