### ISSUE TITLE
Uchiwa module has ancient requirements

### ISSUE THREAD

**Issue by llauren** [Yelp/puppet-uchiwa#85]
yelp-uchiwa 1.0.2 and 2.0.0 require:

* Ubuntu Linux version 10.04 or 12.04
* puppet 3.x
* puppetlabs-apt &lt; 3.0

These requirements are ancient, and in many cases, no longer supported (or secure). Because of these requirements, i cannot update the uchiwa module without force or other nasty means.

Suggest code review and requirements bump-up to:

* Ubuntu 14.04 and 16.04
* puppet 4.x (and eventually, 5.x)
* puppetlabs-apt &lt; 5

**Comment by xraystyle** [comment]
I'll add another comment seconding this. Dinosaurs roamed the earth back when Ubuntu 12.04 was released. I'd like to keep using this module, but this is making it rather difficult.

**Comment by solarkennedy** [comment]
Whoa, 1 year anniversary. 
These things are not strictly true, we use this module at yelp and we run much more modern stuff.

Would anyone care to make a PR?

**Comment by xraystyle** [comment]
@solarkennedy I'm looking at it now, there's no Modulefile in the repo listing the info/dependencies. Am I missing something here?

**Comment by solarkennedy** [comment]
The Modulefile format has been deprecated. metadata.json is used now
https://docs.puppet.com/puppet/4.4/modules_metadata.html

**Comment by xraystyle** [comment]
Gotcha. I've created a pull. https://github.com/Yelp/puppet-uchiwa/pull/92
